language: java

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

before_install:
  - sudo apt-get update -qq
  - mvn install:install-file -Dfile=libs/cordova-2.5.0.jar -DgroupId=org.apache.cordova -DartifactId=cordova -Dversion=2.5.0 -Dclassifier=android -Dpackaging=jar
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - wget http://dl.google.com/android/android-sdk_r20.0.3-linux.tgz
  - tar -zxf android-sdk_r20.0.3-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --filter 1,2,11 --no-ui --force
