language: java
before_install:
  - mvn install:install-file -Dfile=libs/phonegap-1.3.0.jar -DgroupId=org.apache.cordova -DartifactId=cordova -Dversion=1.3.0 -Dclassifier=android -Dpackaging=jar
  - wget http://dl.google.com/android/android-sdk_r18-linux.tgz
  - tar -zxf android-sdk_r18-linux.tgz
  - export ANDROID_HOME=~/builds/SpeedTracks/SPT-PhoneGap-AndroidClient/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --filter 1,2,11 --no-ui --force